# Interactive component

```{r }
library(readr)
library(vcd)
library(ggalluvial)
library(dplyr)
library(plotly)
library(d3r)
library(tidyverse)
library(leaflet)
library(formattable)
```


```{r,echo=FALSE, results="asis"}
library(readr)
library("jsonlite")

circuits <- read_csv("data/circuits.csv")
constructor_results <- read_csv("data/constructor_results.csv")
constructor_standings <- read_csv("data/constructor_standings.csv")
constructors <- read_csv("data/constructors.csv")
driver_standings <- read_csv("data/driver_standings.csv")
drivers <- read_csv("data/drivers.csv")
lap_times <- read_csv("data/lap_times.csv")
pit_stops <- read_csv("data/pit_stops.csv")
qualifying <- read_csv("data/qualifying.csv")
races <- read_csv("data/races.csv")
results <- read_csv("data/results.csv")
status <- read_csv("data/status.csv")

cat(
  paste(
  '<script>
    var data = ',toJSON(circuits),';
  </script>'
  , sep="")
)
```

<html lang="en-US">
<meta charset="utf-8">
<head>
  <!-- Load in the d3 library -->
  <script src="https://d3js.org/d3.v7.js"></script>
  
<style>
</style>
</head>

<body>
  <svg align = center width="1600" height="800"> 
    <!-- Add your SVG elements here -->   
  </svg> 

<script>

d3.csv("https://github.com/ashkan-bozorgzad/F1_EDAV_Project/blob/decf7527793a05e1a67a491219c6e7e5e91b3cd7/data/races.csv", function(data) {
});

</script>
</body>
</html>

